import { University, Destination, BlogPost, Scholarship } from './types';

export const UNIVERSITIES: University[] = [
  {
    id: 'u1',
    name: 'University of Toronto',
    country: 'Canada',
    city: 'Toronto',
    logo: 'https://imgur.com/ZuHgAJs.png',
    image: 'https://imgur.com/ZuHgAJs.png',
    description: 'A global leader in research and teaching, the University of Toronto offers an unmatched range of undergraduate and graduate programs.',
    tuitionRange: { min: 25000, max: 60000 },
    programs: ['Computer Science', 'Engineering', 'Business', 'Medicine'],
    degreeLevels: ['Undergraduate', 'Postgraduate', 'Doctorate'],
    ranking: 18,
    scholarshipAvailable: true,
    requirements: ['High School Diploma', 'IELTS 6.5+', 'Personal Statement'],
  },
  {
    id: 'u2',
    name: 'Technical University of Munich',
    country: 'Germany',
    city: 'Munich',
    logo: 'https://imgur.com/sSfPxEL.png',
    image: 'https://imgur.com/ZuHgAJs.png',
    description: 'TUM is one of Europe’s leading universities. It is focused on engineering and natural sciences, medicine, and social sciences.',
    tuitionRange: { min: 0, max: 3000 },
    programs: ['Mechanical Engineering', 'Data Science', 'Physics', 'Management'],
    degreeLevels: ['Undergraduate', 'Postgraduate'],
    ranking: 37,
    scholarshipAvailable: true,
    requirements: ['Entrance Exam', 'German Proficiency B2/C1', 'Strong Math background'],
  },
  {
    id: 'u3',
    name: 'University of Oxford',
    country: 'UK',
    city: 'Oxford',
    logo: 'https://imgur.com/xzxXafo.png',
    image: 'https://imgur.com/sSfPxEL.png',
    description: 'The oldest university in the English-speaking world, Oxford is a unique and historic institution.',
    tuitionRange: { min: 35000, max: 80000 },
    programs: ['Law', 'History', 'Philosophy', 'Artificial Intelligence'],
    degreeLevels: ['Postgraduate', 'Doctorate', 'MBA'],
    ranking: 3,
    scholarshipAvailable: true,
    requirements: ['First Class Honors', 'Reference Letters', 'GRE/GMAT for MBA'],
  },
  {
    id: 'u4',
    name: 'Harvard University',
    country: 'USA',
    city: 'Cambridge',
    logo: 'https://imgur.com/MZnOZDW.png',
    image: 'https://imgur.com/xzxXafo.png',
    description: 'Harvard University is committed to excellence in teaching, learning, and research, and to developing leaders in many disciplines who make a difference globally.',
    tuitionRange: { min: 50000, max: 90000 },
    programs: ['Global Affairs', 'Business Administration', 'Public Policy', 'Biology'],
    degreeLevels: ['Undergraduate', 'Postgraduate', 'MBA'],
    ranking: 4,
    scholarshipAvailable: true,
    requirements: ['High SAT/ACT scores', 'Proven Leadership', 'Exceptional Essays'],
  },
  {
    id: 'u5',
    name: 'University of Hertfordshire',
    country: 'UK',
    city: 'Hatfield',
    logo: 'https://imgur.com/ifHyTLz.png',
    image: 'https://imgur.com/MZnOZDW.png',
    description: 'The University of Hertfordshire is an innovative and vocational university with an excellent reputation for producing industry-ready graduates.',
    tuitionRange: { min: 14000, max: 22000 },
    programs: ['Business', 'Aerospace Engineering', 'Law', 'Pharmacy'],
    degreeLevels: ['Undergraduate', 'Postgraduate'],
    ranking: 600,
    scholarshipAvailable: true,
    isPartner: true,
    requirements: ['IELTS 6.0+', 'High School Certificate', 'Personal Statement'],
  },
  {
    id: 'u6',
    name: 'University of Worcester',
    country: 'UK',
    city: 'Worcester',
    logo: 'https://imgur.com/ZuHgAJs.png',
    image: 'https://imgur.com/ifHyTLz.png',
    description: 'Worcester is a high-quality university with an excellent reputation for nursing and healthcare, education, and sports.',
    tuitionRange: { min: 13500, max: 18000 },
    programs: ['Nursing', 'Sports Science', 'Education', 'Business'],
    degreeLevels: ['Undergraduate', 'Postgraduate', 'Nursing'],
    ranking: 800,
    scholarshipAvailable: true,
    isPartner: true,
    requirements: ['IELTS 6.0+', 'Academic References', 'Portfolio for specific courses'],
  }
];

export const DESTINATIONS: Destination[] = [
  {
    id: 'd1',
    name: 'Canada',
    image: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&q=80&w=800',
    description: 'Known for high-quality education and high living standards.',
    visaRequirements: 'Study Permit required. Proof of funds, Acceptance letter, and medical exam.',
    costOfLiving: 'Approx $1,500 - $2,500 CAD per month.',
    popularCities: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'],
    weather: 'Four distinct seasons. Cold winters, warm summers.',
    lifestyle: 'Multicultural, outdoorsy, safe and friendly.',
    workOpportunities: 'Post-graduation work permit (PGWP) up to 3 years.',
    accommodation: 'On-campus dorms, off-campus shared rentals.',
  },
  {
    id: 'd2',
    name: 'Germany',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&q=80&w=800',
    description: 'Tuition-free public universities and a powerhouse of engineering.',
    visaRequirements: 'National Visa (D) for study. Blocked account with €11,208.',
    costOfLiving: 'Approx €800 - €1,200 per month.',
    popularCities: ['Munich', 'Berlin', 'Hamburg', 'Aachen'],
    weather: 'Moderate continental climate.',
    lifestyle: 'Rich history, efficient public transport, high focus on work-life balance.',
    workOpportunities: '18-month job seeker visa post-graduation.',
    accommodation: 'Studentenwerk (dormitories) are highly competitive and affordable.',
  },
  {
    id: 'd3',
    name: 'United Kingdom',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&q=80&w=800',
    description: 'Home to some of the world’s most prestigious universities.',
    visaRequirements: 'Student Visa (Tier 4). CAS from university, Financial proof.',
    costOfLiving: 'Approx £1,000 - £1,500 per month (£1,800+ in London).',
    popularCities: ['London', 'Manchester', 'Edinburgh', 'Bristol'],
    weather: 'Changeable, cool and rainy but mild.',
    lifestyle: 'Cosmopolitan, historic, vibrant arts and music scene.',
    workOpportunities: 'Graduate Route allows 2 years post-study work.',
    accommodation: 'Private student halls, shared houses.',
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'How to Ace Your Study Visa Interview',
    excerpt: 'Expert tips on answering questions about your choice of course, country, and future plans.',
    content: 'Long form content here...',
    category: 'Visa Guides',
    author: 'Sarah Johnson',
    date: '2024-03-15',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'b2',
    title: 'Top 5 Scholarships for International Students in 2024',
    excerpt: 'Detailed list of fully funded opportunities for undergraduate and master students.',
    content: 'Long form content here...',
    category: 'Scholarships',
    author: 'Michael Chen',
    date: '2024-03-10',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=800',
  }
];

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: 's1',
    title: 'Global Excellence Scholarship',
    provider: 'Travelplanner Foundation',
    amount: 'Full Tuition',
    type: 'Full',
    deadline: '2024-08-30',
    description: 'Supporting high-achieving students from developing nations.',
    eligibility: ['GPA 3.8+', 'Leadership proof', 'Offer letter from partner uni'],
  },
  {
    id: 's2',
    title: 'Tech Innovators Grant',
    provider: 'Silicon Valley Partners',
    amount: '$10,000',
    type: 'Merit-based',
    deadline: '2024-06-15',
    description: 'For students pursuing Computer Science and AI.',
    eligibility: ['Project portfolio', 'Enrollment in CS program'],
  }
];
